In [ ]:
Consider the below code to answer further questions:
import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)

In [ ]:
Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [2]:
import numpy as np

In [3]:
list_example = [1,2,3, 'a','b','c']

In [4]:
array_example = np.array([1,2,3])

print(f'The data type of list_example is :{type(list_example)}')

The data type of list_example is :<class 'list'>


In [5]:
print(f'The data type of array_example is :{type(array_example)}')

The data type of array_example is :<class 'numpy.ndarray'>


In [6]:
import array

In [7]:
list_example = [1,2,3,'a','b','c']

In [8]:
array_example = array.array('i',[1,2,3])
print(f'The data type of list_example is :{type(list_example)}')


The data type of list_example is :<class 'list'>


In [9]:
print(f'The data type of array_example is :{type(array_example)}')

The data type of array_example is :<class 'array.array'>


In [ ]:
Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [10]:
list_=[1,'string',3.14,True]

In [11]:
arra_list =[[1,2,3],{'key':'value'},(4,5),None]

In [12]:
def print_data_types(variable,variable_name):
    print(f"Data type in {variable_name}:")
    for index,element in enumerate(variable):
        print(f"Element{index} is of type{type(element).__name__}")

In [14]:
print_data_types(list_, "list_")
print_data_types(arra_list,"arra_list")

Data type in list_:
Element0 is of typeint
Element1 is of typestr
Element2 is of typefloat
Element3 is of typebool
Data type in arra_list:
Element0 is of typelist
Element1 is of typedict
Element2 is of typetuple
Element3 is of typeNoneType


In [ ]:
Q3. Considering the following changes in the variable, array_list:
array_list = np.array(object = list_, dtype = int)

In [15]:
import numpy as np

In [16]:
list_=[1,'string',3.14, True]

In [17]:
try:
    array_list =np.array(object=list_, dtype=int)
except ValueError as e:
    print(f"Error converting list_ to aray_list with dtype=int:{e}")
    array_list = None
    

Error converting list_ to aray_list with dtype=int:invalid literal for int() with base 10: 'string'


In [18]:
def print_data_types(variable,variable_name):
    if variable is None:
        print(f"{variable_name} is not defined due to conversion error . ")
        return
    print(f"Data types in {variable_name}:")
    for index,element in enumerate(variable):
        print(f"Element{index} is of type{type(element).__name__}")

In [19]:
print_data_types(list_, "list_")
if array_list is not None:
    print_data_types(array_list,"array_list")

Data types in list_:
Element0 is of typeint
Element1 is of typestr
Element2 is of typefloat
Element3 is of typebool


In [ ]:
Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [20]:
import numpy as np

In [21]:
num_array = np.array([[1,2,3],[4,5,6]])

In [22]:
shape = num_array.shape
size= num_array.size

In [23]:
print("Shape of num_array:",shape)

Shape of num_array: (2, 3)


In [24]:
print("Size of num_array:",size)

Size of num_array: 6


In [ ]:
Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.

In [26]:
import numpy as np

In [27]:
zero_matrix = np.zeros((3,3))

In [28]:
print("3*3 Matrix of zeros:")
print(zero_matrix)

3*3 Matrix of zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [29]:
import numpy as np

In [30]:
identity_matrix = np.eye(5)

In [31]:
print("5*5 Identity Matrix:")
print(identity_matrix)

5*5 Identity Matrix:
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [32]:
import numpy as np

In [ ]:
identity_matrix = np.identity(5